server:
  port: 8082

spring:
  application:
    name: demo
  data:
    mongodb:
      uri: mongodb://localhost:27017/corpus_dataset
    elasticsearch:
      # 访问集群名称  my-application
      cluster-name: my-application
      # 注意不要写协议名，否则会报错(访问节点ip和端口号)
      cluster-nodes: 192.168.233.136:9300

  profiles:
    active: dev

  freemarker:
    cache: false
    check-template-location: true
    content-type: text/html
    enabled: true
    suffix: .ftl
    template-loader-path: classpath:/templates/


#监控
management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: httptrace,refresh,health,info
  # 关闭actuator对es的监控
  health:
    elasticsearch:
      enabled: false

info:
  model:
    name: demo
    version: 1.0.0
    port: 8082


#logging:
#  config: classpath:log4j2-dev.xml

#日志
logback:
  logdir: D:\log

#fastDFS的配置
fdfs:
  so-timeout: 30000  #读取时间
  connect-timeout: 30000      # 连接超时时间
  thumb-image:      # 缩略图的参数
    height: 150
    width: 150
  tracker-list: 192.168.233.131:22122   # tracker-server的IP加端口，多个tracker用逗号隔开
  pool:
    max-total: 500
    max-wait-millis: 30000
  web-server-url: http://192.168.233.131:8888/ # 供于下载返回完整路径








